# Generated by Django 4.0.4 on 2022-06-01 05:59

import curatorapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='bible/img/')),
                ('content', models.TextField(null=True)),
                ('mp3', models.FileField(upload_to='bible/mp3/', validators=[curatorapp.validators.validate_file_extension])),
            ],
        ),
        migrations.CreateModel(
            name='Permanent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='permanent/img/')),
                ('content', models.TextField(null=True)),
                ('mp3', models.FileField(upload_to='permanent/mp3/', validators=[curatorapp.validators.validate_file_extension])),
            ],
        ),
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='special/img/')),
                ('content', models.TextField(null=True)),
                ('mp3', models.FileField(upload_to='special/mp3/', validators=[curatorapp.validators.validate_file_extension])),
            ],
        ),
    ]
